apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-config
  namespace: quorum
  labels:
    app.kubernetes.io/part-of: quorum
data:
  # Database
  DATABASE_HOST: "database-1.cluster-cvs68yyk49gx.eu-north-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres"
  DATABASE_NAME: "postgres"
  DATABASE_IAM_AUTH: "true"

  # Redis
  REDIS_PORT: "6379"
  # REDIS_HOST is overridden per environment (ElastiCache endpoint)

  # LiveKit
  LIVEKIT_URL: "wss://quorum-oor689rg.livekit.cloud"

  # S3
  S3_REGION: "eu-north-1"

  # Frontend (public)
  NEXT_PUBLIC_LIVEKIT_URL: "wss://quorum-oor689rg.livekit.cloud"

  # Datadog
  DD_ENV: "production"
  DD_LOGS_INJECTION: "true"
  DD_TRACE_SAMPLE_RATE: "1"
  DD_PROFILING_ENABLED: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
